cluster.name: elasticsearch-nomad
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
network.host: 0.0.0.0
cluster.initial_master_nodes: [ "${HOSTNAME}" ]
xpack.license.self_generated.type: basic
xpack.security.enabled: false
