---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: centos
    box: bento/centos-7.9
  - name: ubuntu
    box: bento/ubuntu-21.04
provisioner:
  name: ansible
  playbook:
    prepare: prepare.yml
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
