---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: instance
    box: bento/centos-7.9
provisioner:
  name: ansible
  playbook:
    prepare: prepare.yml
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8