---
- name: Prepare
  hosts: all

  tasks:
    - name: start firewall
      when: ansible_facts['os_family'] == "RedHat"
      systemd:
        name: firewalld
        state: started
      become: true
