---
- name: install grafana (Redhat)
  when: ansible_facts['os_family'] == "RedHat"
  yum:
    name: https://dl.grafana.com/oss/release/grafana-{{ grafana_version }}-1.x86_64.rpm
    state: present

- name: install grafana (Debian)
  when: ansible_facts['os_family'] == "Debian"
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_{{ grafana_version }}_amd64.deb

- name: create grafana folder
  file:
    name: /var/lib/grafana/plugins
    state: directory
    owner: root
    group: root
    mode: '755'

- name: get grafana piechart panel
  unarchive:
    src: https://grafana.com/api/plugins/grafana-piechart-panel/versions/latest/download
    remote_src: true
    dest: /var/lib/grafana/plugins

- name: get grafana natel discrete panel
  unarchive:
    src: https://grafana.com/api/plugins/natel-discrete-panel/versions/latest/download
    remote_src: true
    dest: /var/lib/grafana/plugins
