---
- name: create jaeger user
  user:
    name: jaeger
    shell: /bin/false
    create_home: false

- name: create /etc/jaeger
  file:
    path: /etc/jaeger
    state: directory
    owner: jaeger
    group: jaeger
    mode: '755'

- name: create /var/lib/jaeger
  file:
    path: /var/lib/jaeger
    state: directory
    owner: jaeger
    group: jaeger
    mode: '755'

- name: get jaeger
  get_url:
    timeout: 60
    url: https://github.com/jaegertracing/jaeger/releases/download/v{{ jaeger_version }}/jaeger-{{ jaeger_version }}-linux-amd64.tar.gz
    dest: /tmp/
    mode: '644'

- name: unarchive jaeger
  unarchive:
    src: /tmp/jaeger-{{ jaeger_version }}-linux-amd64.tar.gz
    dest: /tmp/


- name: copy jaeger-agent
  copy:
    src: /tmp/jaeger-{{ jaeger_version }}-linux-amd64/jaeger-agent
    dest: /usr/local/bin/
    remote_src: true
    owner: jaeger
    group: jaeger
    mode: +x

- name: copy jaeger-collector
  copy:
    src: /tmp/jaeger-{{ jaeger_version }}-linux-amd64/jaeger-collector
    dest: /usr/local/bin/
    remote_src: true
    owner: jaeger
    group: jaeger
    mode: +x

- name: copy jaeger-query
  copy:
    src: /tmp/jaeger-{{ jaeger_version }}-linux-amd64/jaeger-query
    dest: /usr/local/bin/
    remote_src: true
    owner: jaeger
    group: jaeger
    mode: +x

- name: copy jaeger-all-in-one
  copy:
    src: /tmp/jaeger-{{ jaeger_version }}-linux-amd64/jaeger-all-in-one
    dest: /usr/local/bin/
    remote_src: true
    owner: jaeger
    group: jaeger
    mode: +x

- name: get jaeger lib
  get_url:
    url: https://github.com/jaegertracing/jaeger-client-cpp/releases/download/{{ jaeger_cpp_version }}/libjaegertracing_plugin.linux_amd64.so
    dest: /usr/local/lib/libjaegertracing_plugin.so
    mode: '644'
    owner: root
    group: root

- name: cleanup
  file:
    path: /tmp/jaeger-{{ jaeger_version }}-linux-amd64
    state: absent
