
- name: install node_exporter
  include_role:
    name: "cloudalchemy.node_exporter"

- name: copy prometheus.service
  copy:
    src: node-exporter-service.json
    dest: /etc/consul.d/node-exporter-service.json
    owner: consul
    group: consul
    mode: '644'
