---
- name: Prepare
  hosts: all
  tasks:
    - name: "Include hc_stack_install/prerequisites"
      include_role:
        name: "hc_stack_install"
        tasks_from: prerequisites
        apply:
          become: true
