---
- name: copy docker-login.service
  copy:
    src: docker-login.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: '644'

- name: copy docker-login.sh
  copy:
    src: docker-login.sh
    dest: /usr/local/bin/
    mode: +x
    owner: root
    group: root

- name: enable docker-login service
  systemd:
    name: docker-login
    enabled: yes

- name: periodically restart docker-login.service
  cron:
    name: restart docker-login.service
    minute: '*/15'
    job: /usr/bin/systemctl restart docker-login.service
