---
- name: download script
  get_url:
    url: https://dl.google.com/cloudagents/add-monitoring-agent-repo.sh
    dest: /tmp/add-monitoring-agent-repo.sh

- name: run script
  command: "bash /tmp/add-monitoring-agent-repo.sh" # noqa 301

- name: install stackdriver-agent (RedHat)
  when: ansible_facts['os_family'] == "RedHat"
  yum:
    name: stackdriver-agent
    state: present

- name: install stackdriver-agent (Debian)
  when: ansible_facts['os_family'] == "Debian"
  apt:
    name: stackdriver-agent
    state: present

- name: enable stackdriver-agent
  systemd:
    name: stackdriver-agent
    enabled: yes
