---
- name: download script
  get_url:
    url: https://dl.google.com/cloudagents/add-monitoring-agent-repo.sh
    dest: /tmp/add-monitoring-agent-repo.sh

- name: run script
  command: "bash /tmp/add-monitoring-agent-repo.sh" # noqa 301

- name: install stackdriver-agent (RedHat)
  when: ansible_facts['os_family'] == "RedHat"
  register: agent_check_rh
  yum:
    name: stackdriver-agent
    state: present

- name: install stackdriver-agent (Debian)
  when: ansible_facts['os_family'] == "Debian"
  register: agent_check_deb
  ignore_errors: yes
  apt:
    name: stackdriver-agent
    state: present
    update_cache: yes

- name: enable stackdriver-agent
  when: ( not agent_check_deb is failed and agent_check_rh is skipped ) or ( not agent_check_rh is failed and agent_check_deb is skipped )
  systemd:
    name: stackdriver-agent
    enabled: yes
