---
- name: create dnsmasq.conf
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf

- name: retrieve interface
  command: /bin/bash -c "/sbin/ip route | grep '^default' | grep -Po '(?<=dev )(.+?)(?= )'"
  register: interface

- name: add PEERDNS to interface config
  lineinfile:
    path: '/etc/sysconfig/network-scripts/ifcfg-{{interface.stdout}}'
    regex: ^PEERDNS=
    line: PEERDNS=no

- name: add DNS1 to interface config
  lineinfile:
    path: '/etc/sysconfig/network-scripts/ifcfg-{{interface.stdout}}'
    regex: ^DNS1=
    line: DNS1=127.0.0.1

- name: enable and start dnsmasq
  systemd:
    name: dnsmasq
    enabled: yes
    state: started

- name: update resolv.conf
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    attributes: +i
