---
# vars file for hc_stack_install

extra_packages:
  - wget
  - unzip
  - jq
  - dnsmasq
  #  - openjdk-8-jdk
  - java-1.8.0-openjdk
  - bind-utils
  - tcpdump

install_terraform: true
install_vault: true
install_consul: true
install_nomad: true
install_envoy: true
install_cni: true
install_docker: true

consul_enterprise: no
nomad_enterprise: no
vault_enterprise: no

terraform_version: 1.0.4
vault_version: 1.8.1
consul_version: 1.10.1
consul_esm_version: 0.5.0
nomad_version: 1.1.3
envoy_version: 1.18.2.p0.gd362e79-1p75.g76c310e
cni_version: 0.9.1
containerd_version: 1.4.9-3.1
docker_ce_version: 20.10.8-3
docker_scan_version: 0.8.0-3

dummy_ip: 192.168.0.1

nameservers:
  - 8.8.8.8
