---
# vars file for hc_stack_install

extra_packages:
  - wget
  - unzip
  - jq
  - dnsmasq
  #  - openjdk-8-jdk
  - java-1.8.0-openjdk
  - bind-utils
  - tcpdump

install_terraform: true
install_vault: true
install_consul: true
install_nomad: true
install_envoy: true
install_cni: true
install_docker: true

consul_enterprise: no
nomad_enterprise: no
vault_enterprise: no

terraform_version: 0.15.5
vault_version: 1.7.2
consul_version: 1.9.6
consul_esm_version: 0.5.0
nomad_version: 1.1.1
envoy_version: 1.16.4.p0.gbf5d0eb-1p74.gbb8060d
cni_version: 0.9.1
containerd_version: 1.4.6-3.1
docker_ce_version: 20.10.7-3
docker_scan_version: 0.8.0-3

dummy_ip: 192.168.0.1

nameservers:
  - 8.8.8.8
