---
# vars file for hc_stack_install

extra_packages:
  - wget
  - unzip
  - jq
  - tcpdump
  - dnsmasq

extra_packages_redhat:
  - java-1.8.0-openjdk
  - bind-utils
  - nc

extra_packages_debian:
  - openjdk-8-jdk
  - dnsutils
  - network-manager
  - firewalld
  - acl

install_terraform: true
install_vault: true
install_consul: true
install_nomad: true
install_envoy: true
install_cni: true
install_docker: true

consul_enterprise: false
nomad_enterprise: false
vault_enterprise: false

terraform_version: 1.4.2
vault_version: 1.13.0
consul_version: 1.15.1
consul_esm_version: 0.7.1
nomad_version: 1.5.1
cni_version: 1.2.0
containerd_version: 1.6.18-3.1
docker_ce_version: 23.0.1-1
docker_scan_version: 0.23.0-1

dummy_ip: 192.168.0.1

nameservers:
  - 8.8.8.8
