---
- name: import Microsoft key
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: add Microsoft repository
  yum_repository:
    name: azure-cli
    baseurl: https://packages.microsoft.com/yumrepos/azure-cli
    enabled: 1
    gpgcheck: 1
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    file: azure-cli
    description: Repo for Azure CLI

- name: install Azure CLI
  yum:
    name: azure-cli
    state: present
