---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: instance
    box: bento/centos-7.9
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
verifier:
  name: ansible
