---
- name: Setup baseline
  hosts: all
  become: yes
  tasks:
    - name: "Include hc_stack_install"
      include_role:
        name: "hc_stack_install"

- name: Setup AWS only resources
  hosts: aws
  become: yes
  tasks:
    - name: "Include hc_stack_aws"
      include_role:
        name: "hc_stack_aws"

- name: Setup AZURE only resources
  hosts: azure
  become: yes
  tasks:
    - name: "Include hc_stack_azure"
      include_role:
        name: "hc_stack_azure"

- name: Setup GCP only resources
  hosts: gcp
  become: yes
  tasks:
    - name: "Include hc_stack_gcp"
      include_role:
        name: "hc_stack_gcp"

- name: Setup apps component
  hosts: all
  become: yes
  tasks:
    - name: "Include hc_stack_apps"
      include_role:
        name: "hc_stack_apps"
