---
- name: Setup on Azure
  hosts: all
  become: yes
  tasks:
    - name: "Include hc_stack_install"
      include_role:
        name: "hc_stack_install"
    - name: "Include hc_stack_azure"
      include_role:
        name: "hc_stack_azure"
    - name: "Include hc_stack_apps"
      include_role:
        name: "hc_stack_apps"
