---
- name: Setup on AWS
  hosts: all
  become: yes
  tasks:
    - name: "Include hc_stack_install"
      include_role:
        name: "hc_stack_install"
    - name: "Include hc_stack_aws"
      include_role:
        name: "hc_stack_aws"
    - name: "Include hc_stack_apps"
      include_role:
        name: "hc_stack_apps"
