---
- name: create /opt/cni/bin/ folder
  file:
    path: /opt/cni/bin/
    state: directory
    owner: root
    group: root
    mode: '755'

- name: install cni
  unarchive:
    src: https://github.com/containernetworking/plugins/releases/download/v{{ cni_version }}/cni-plugins-linux-amd64-v{{ cni_version }}.tgz
    dest: /opt/cni/bin/
    remote_src: yes

- name: copy bridge.conf
  copy:
    src: bridge.conf
    dest: /etc/sysctl.d/bridge.conf
    owner: root
    group: root
    mode: '644'
