---
- name: install envoy
  yum:
    name: https://rpm.dl.getenvoy.io/public/rpm/any-distro/any-version/x86_64/getenvoy-envoy-{{ envoy_version }}.x86_64.rpm
    state: present

- name: rm envoy binary
  ansible.builtin.file:
    path: /usr/bin/envoy
    state: absent

- name: copy envoy binary
  copy:
    src: /opt/getenvoy/bin/envoy
    dest: /usr/bin/envoy
    remote_src: yes
    owner: root
    group: root
    mode: a+x
