---
- name: Add envoy keyring (RedHat)
  when: ansible_facts['os_family'] == "RedHat"
  ansible.builtin.rpm_key:
    state: present
    key: https://rpm.dl.getenvoy.io/public/gpg.CF716AF503183491.key

- name: Add envoy repo (RedHat)
  when: ansible_facts['os_family'] == "RedHat"
  ansible.builtin.yum_repository:
    name: tetrate-getenvoy-rpm-stable
    description:  GeteEnvoy RPM Packages
    file: tetrate-getenvoy-rpm-stable
    baseurl: https://rpm.dl.getenvoy.io/public/rpm/el/7/$basearch
    repo_gpgcheck: true
    enabled: true
    gpgkey: https://rpm.dl.getenvoy.io/public/gpg.CF716AF503183491.key
    gpgcheck: true
    metadata_expire: 300

- name: install envoy (RedHat)
  when: ansible_facts['os_family'] == "RedHat"
  ansible.builtin.yum:
    name: getenvoy-envoy
    update_cache: true
    state: present

- name: Add envoy keyring (Debian)
  when: ansible_facts['os_family'] == "Debian"
  ansible.builtin.apt_key:
    url: https://deb.dl.getenvoy.io/public/gpg.8115BA8E629CC074.key
    keyring: /etc/apt/trusted.gpg.d/getenvoy-keyring.gpg

- name: Add envoy repo (Debian)
  when: ansible_facts['os_family'] == "Debian"
  ansible.builtin.apt_repository:
    repo: deb https://deb.dl.getenvoy.io/public/deb/ubuntu {{ ansible_lsb['codename'] }} main
    state: present
    filename: getenvoy

- name: install envoy (Debian)
  when: ansible_facts['os_family'] == "Debian"
  apt:
    name: getenvoy-envoy
    update_cache: true
    state: present

- name: rm envoy binary (RedHat)
  when: ansible_facts['os_family'] == "RedHat"
  ansible.builtin.file:
    path: /usr/bin/envoy
    state: absent

- name: copy envoy binary (RedHat)
  when: ansible_facts['os_family'] == "RedHat"
  copy:
    src: /opt/getenvoy/bin/envoy
    dest: /usr/bin/envoy
    remote_src: true
    owner: root
    group: root
    mode: a+x
