---
- name: update system packages
  yum:
    update_only: yes
    state: latest # noqa 403
    exclude: epel-release,grub2*,shim*,mokutil

- name: install epel-release
  yum:
    name: epel-release
    state: present

- name: install extra packages
  yum:
    name: '{{ extra_packages }}'
    state: present

- name: create certsreaders group
  group:
    name: certsreaders
    state: present
