name: "CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup SSH Keys and known_hosts
        env:
          PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        run: |
          SSH_PATH="$HOME/.ssh"
          mkdir -p "$SSH_PATH"
          touch "$SSH_PATH/known_hosts"
          echo "$PRIVATE_KEY" > "$SSH_PATH/id_rsa"
          chmod 700 "$SSH_PATH"
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 600 "$SSH_PATH/known_hosts"
          chmod 600 "$SSH_PATH/id_rsa"
          eval $(ssh-agent)
          ssh-add "$SSH_PATH/id_rsa"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.4

      - name: Terraform Format
        id: fmt
        run: cd terraform && terraform fmt -check -recursive

      - name: Terraform Init
        id: init
        run: cd terraform && terraform init -backend=false

      - name: Terraform Validate
        id: validate
        run: cd terraform && terraform validate

  ansible:
    name: "Ansible"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@master
        with:
          targets: "ansible/roles/*/"

  release:
    name: "Release"
    runs-on: ubuntu-20.04
    needs:
      - terraform
      - ansible
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bump version and push tag
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
