name: "TF Cloud"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cloud: [ "aws", "gcp", "azure" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.4
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: cd terraform && terraform fmt -check

      - name: Terraform Backend
        shell: bash
        env:
          CLOUD: ${{ matrix.cloud }}
        run: |
          cat > terraform/backend.tf << EOF
          terraform {
            backend "remote" {
              hostname     = "app.terraform.io"
              organization = "bitrock"
              workspaces {
                name = "caravan-baking-${CLOUD}"
              }
            }
          }
          EOF

      - name: Terraform Init
        id: init
        run: cd terraform && terraform init

      - name: Terraform Validate
        id: validate
        run: cd terraform && terraform validate -no-color

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: cd terraform && terraform apply -auto-approve
        env:
          TF_VAR_build_on_google: ${ matrix.cloud == "gcp" }
          TF_VAR_build_on_aws: ${ matrix.cloud == "aws" }
          TF_VAR_build_on_azure: ${ matrix.cloud == "azure" }
